name: Main

on:
  push:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run format:check

      - name: Run linting
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Generate OpenAPI schema
        run: npm run generate

      - name: Check for uncommitted changes
        run: |
          if ! git diff --quiet; then
            echo "Error: There are uncommitted changes after running 'npm run generate'."
            echo "This indicates that the generated schema is not in sync with the source code."
            echo "Please run 'npm run generate' locally and commit the updated files."
            echo ""
            echo "Changed files:"
            git diff --name-only
            exit 1
          fi

      - name: Validate OpenAPI schema
        run: npm run validate
        env:
          REDOCLY_TELEMETRY: 'off'

      - name: Run tests
        run: npm test
